/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ir97j8;


import static ir97j8.FileIO.*;
import static ir97j8.dinosaurs.*;
import static java.lang.Double.parseDouble;
import java.util.ArrayList;

/**
 *
 * @author Nyulasi Ákos
 */
public class addDino extends javax.swing.JFrame {
public static ArrayList<dinosaurs> dinos = new ArrayList<dinosaurs>();
    /**
     * Creates new form addDino
     */
    public addDino() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        InName = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        InDescription = new javax.swing.JTextArea();
        Title = new javax.swing.JLabel();
        LName = new javax.swing.JLabel();
        LType = new javax.swing.JLabel();
        LLength = new javax.swing.JLabel();
        LHeight = new javax.swing.JLabel();
        LWeight = new javax.swing.JLabel();
        InLength = new javax.swing.JTextField();
        LDescription = new javax.swing.JLabel();
        InHeight = new javax.swing.JTextField();
        InWeight = new javax.swing.JTextField();
        BNo = new javax.swing.JButton();
        BClear = new javax.swing.JButton();
        BSave = new javax.swing.JButton();
        LError = new javax.swing.JLabel();
        LSaved = new javax.swing.JLabel();
        InType = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Új dinoszaurusz");
        setBackground(new java.awt.Color(153, 255, 153));
        setFocusable(false);

        jPanel1.setBackground(new java.awt.Color(153, 255, 153));

        InName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InNameActionPerformed(evt);
            }
        });

        InDescription.setColumns(20);
        InDescription.setRows(5);
        jScrollPane1.setViewportView(InDescription);

        Title.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        Title.setText("Új dinoszaurusz felvétele");

        LName.setText("Neve:");

        LType.setText("Besorolása:");

        LLength.setText("Hosszúság:");

        LHeight.setText("Magasság:");

        LWeight.setText("Súly:");

        InLength.setToolTipText("Értékét a példának megfelelően adja meg: 6.5");

        LDescription.setText("Leírás:");

        InHeight.setToolTipText("Értékét a példának megfelelően adja meg: 6.5");

        InWeight.setToolTipText("Értékét a példának megfelelően adja meg: 6.5");

        BNo.setText("Mégse");
        BNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BNoActionPerformed(evt);
            }
        });

        BClear.setText("Visszaállítás");
        BClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BClearActionPerformed(evt);
            }
        });

        BSave.setText("Mentés");
        BSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BSaveActionPerformed(evt);
            }
        });

        LError.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        LError.setForeground(new java.awt.Color(255, 51, 51));
        LError.setText("Hiba a hosszúság, magasság vagy súly megadásánál.");

        LSaved.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        LSaved.setForeground(new java.awt.Color(51, 51, 255));
        LSaved.setText("Mentve");

        InType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Húsevő", "Növényevő" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(LType)
                                    .addComponent(LLength)
                                    .addComponent(LName, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(LWeight)
                                            .addComponent(LHeight)
                                            .addComponent(LDescription))
                                        .addGap(3, 3, 3))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(BClear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(BSave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(BNo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(LSaved)
                                        .addGap(20, 20, 20)))
                                .addGap(0, 36, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane1)
                            .addComponent(InName)
                            .addComponent(InLength)
                            .addComponent(InHeight)
                            .addComponent(InWeight, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                            .addComponent(InType, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(Title)
                        .addGap(45, 45, 45)))
                .addGap(30, 30, 30))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LError)
                .addGap(94, 94, 94))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(Title)
                .addGap(18, 18, 18)
                .addComponent(LError)
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LName))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LType)
                    .addComponent(InType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InLength, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LLength))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InHeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LHeight))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InWeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LWeight))
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(LDescription)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(LSaved)
                        .addGap(18, 18, 18)
                        .addComponent(BSave)
                        .addGap(18, 18, 18)
                        .addComponent(BClear)
                        .addGap(18, 18, 18)
                        .addComponent(BNo)))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        LError.setVisible(false);
        LSaved.setVisible(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void InNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InNameActionPerformed

    private void BSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BSaveActionPerformed
        dinosaurs dino = null;
        String name = InName.getText();
        String type = InType.getSelectedItem().toString();
        String desc = InDescription.getText();
        String Slength = InLength.getText();
        String Sheight = InHeight.getText();
        String Sweight = InWeight.getText();
        if(type == "Húsevő"){
        try{
            Double length = parseDouble(Slength);
            Double height = parseDouble(Sheight);
            Double weight = parseDouble(Sweight);
            
            
            dino = GenerateCarnivore(name,desc,length,height,weight);
            WriteFile(dino.getName(), dino.getType(), dino.getDescription(), dino.getLength(), dino.getHeight(), dino.getWeight());
            
        LError.setVisible(false);
        LSaved.setVisible(true);
        Clear();
        
            
        }
        catch(NumberFormatException ex){
            LError.setVisible(true);
            
        }
        }
        if(type == "Növényevő"){
        try{
            Double length = parseDouble(Slength);
            Double height = parseDouble(Sheight);
            Double weight = parseDouble(Sweight);
            
            
            dino = GenerateHerbivore(name,desc,length,height,weight);
            WriteFile(dino.getName(), dino.getType(), dino.getDescription(), dino.getLength(), dino.getHeight(), dino.getWeight());
            
        LError.setVisible(false);
        LSaved.setVisible(true);
        Clear();
        
            
        }
        catch(NumberFormatException ex){
            LError.setVisible(true);
            
        }
        }
        
      
        
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_BSaveActionPerformed

    private void BClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BClearActionPerformed
        Clear();
        LError.setVisible(false);
        LSaved.setVisible(false);
    }//GEN-LAST:event_BClearActionPerformed

    private void BNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BNoActionPerformed
        super.dispose();
        
    }//GEN-LAST:event_BNoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        CreateFile();
        ReadFile(dinos);
        //LError.setVisible(false);
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addDino.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addDino.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addDino.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addDino.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addDino().setVisible(true);
                
                
            }
        });
    }
    public static void Clear(){
        InName.setText("");
        InType.setSelectedIndex(0);
        InDescription.setText("");
        InLength.setText("");
        InHeight.setText("");
        InWeight.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BClear;
    private javax.swing.JButton BNo;
    private javax.swing.JButton BSave;
    private static javax.swing.JTextArea InDescription;
    private static javax.swing.JTextField InHeight;
    private static javax.swing.JTextField InLength;
    private static javax.swing.JTextField InName;
    private static javax.swing.JComboBox<String> InType;
    private static javax.swing.JTextField InWeight;
    private javax.swing.JLabel LDescription;
    private static javax.swing.JLabel LError;
    private javax.swing.JLabel LHeight;
    private javax.swing.JLabel LLength;
    private javax.swing.JLabel LName;
    private static javax.swing.JLabel LSaved;
    private javax.swing.JLabel LType;
    private javax.swing.JLabel LWeight;
    private javax.swing.JLabel Title;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
